<?php

/**
 * Implements hook_webform_validation_validators().
 *
 * @return array
 */
function webform_password_policy_webform_validation_validators() {
  return array(
    'password_policy' => array(
      'name' => t('Password Policy'),
      'component_types' => array(
        'textfield',
      ),
      'description' => t('Enforces the passwords defined by the Password Policy module.'),
    ),
  );
}

/**
 *
 * @param string $validator_name
 * @param array $items
 * @param array $components
 * @param string $rule
 * @return boolean
 */
function webform_password_policy_webform_validation_validate($validator_name, $items, $components, $rule) {

  if ($validator_name !== 'password_policy') {
    return TRUE;
  }

  $errors = array();

  foreach ($items as $key => $val) {
    $roles = (object) array('roles' => array(2 => 'authenticated user'));
    $raw_error = _password_policy_constraint_validate($val, $roles);

    if (!empty($raw_error)) {
      $errors[] = $raw_error;
    }
  }

  return $errors;
}